config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pairs, only: %i[index create show] do
    get :candles, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candle.rb
class Candle < ApplicationRecord
  belongs_to :pair

  validates :timestamp,
            :open,
            :close,
            :min,
            :max,
            :volume,
            :volumeQuote,
            presence: true
end

app/models/orderbook_ask.rb
class OrderbookAsk < ApplicationRecord
  belongs_to :pair
end

app/models/orderbook_bid.rb
class OrderbookBid < ApplicationRecord
  belongs_to :pair
end

app/models/pair.rb
class Pair < ApplicationRecord
  has_many :trades, dependent: :destroy
  has_many :candles, dependent: :destroy
  has_many :orderbook_asks, dependent: :destroy
  has_many :orderbook_bids, dependent: :destroy
  validates :symbols,
            :baseCurrency,
            :quoteCurrency,
            :quantityIncrement,
            :tickSize,
            :takeLiquidityRate,
            :provideLiquidityRate,
            :feeCurrency,
            presence: true
  validates :symbols, uniqueness: true

  class << self
    def check_shedule
      check_for_new_pairs if need_update?('Pair')
      check_for_trades if need_update?('Trade')
      check_for_orderbook if need_update?('Orderbook')
      check_for_candles if need_update?('Candle')
    end

    private

    def need_update?(type)
      return orderbook_update if type == 'Orderbook'
      type = type.constantize
      type.count < 1 || (Time.now - type.pluck(:created_at).max) / 84_600 > 1
    end

    def orderbook_update
      [OrderbookAsk, OrderbookBid].each { |kind| kind.count < 1 || (Time.now - kind.pluck(:created_at).max) / 84_600 > 1 }
    end

    def check_for_new_pairs
      request('symbol').each do |params|
        Pair.create(symbols: params['id'],
                    baseCurrency: params['baseCurrency'],
                    quoteCurrency: params['quoteCurrency'],
                    quantityIncrement: params['quantityIncrement'],
                    tickSize: params['tickSize'],
                    takeLiquidityRate: params['takeLiquidityRate'],
                    provideLiquidityRate: params['provideLiquidityRate'],
                    feeCurrency: params['feeCurrency'])
      end
    end

    def check_for_trades
      Pair.all.each do |pair|
        request("trades/#{pair.symbols}").each do |params|
          pair.trades.create(trade_id: params['id'],
                             price: params['price'],
                             quantity: params['quantity'],
                             side: params['side'],
                             timestamp: params['timestamp'])
        end
      end
    end

    def check_for_orderbook
      Pair.all.each do |pair|
        orderbook = request("orderbook/#{pair.symbols}")
        create_orderbook('ask', pair, orderbook)
        create_orderbook('bid', pair, orderbook)
      end
    end

    def create_orderbook(type, pair, orderbook)
      orderbook[type.to_s].each do |kind|
        pair.send("orderbook_#{type}s").create(price: kind['price'],
                                               size: kind['size'])
      end
    end

    def check_for_candles
      Pair.all.each do |pair|
        request("candles/#{pair.symbols}").each do |params|
          pair.candles.create(timestamp: params['timestamp'],
                              open: params['open'],
                              close: params['close'],
                              min: params['min'],
                              max: params['max'],
                              volume: params['volume'],
                              volumeQuote: params['volumeQuote'])
        end
      end
    end

    def request(path)
      url = URI("https://api.hitbtc.com/api/2/public/#{path}")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true

      request = Net::HTTP::Get.new(url)

      response = http.request(request)
      JSON.parse(response.read_body)
    end
  end
end

app/models/ticker.rb
class Ticker < ApplicationRecord
  
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :pair

  validates :trade_id,
            :price,
            :quantity,
            :side,
            :timestamp,
            presence: true
  validates :trade_id, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/candles_controller.rb
class CandlesController < ApplicationController
end

app/controllers/orderbook_asks_controller.rb
class OrderbookAsksController < ApplicationController
end

app/controllers/orderbook_bids_controller.rb
class OrderbookBidsController < ApplicationController
end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController
  before_action :load_pair, except: :index

  def index
    @pairs = Pair.all
  end

  def show; end

  def candles
    @candles = @pair.candles
  end

  private

  def load_pair
    @pair = Pair.find params[:id]
  end
end

app/controllers/tickers_controller.rb
class TickersController < ApplicationController
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candles_helper.rb
module CandlesHelper
end

app/helpers/orderbook_asks_helper.rb
module OrderbookAsksHelper
end

app/helpers/orderbook_bids_helper.rb
module OrderbookBidsHelper
end

app/helpers/pairs_helper.rb
module PairsHelper
end

app/helpers/tickers_helper.rb
module TickersHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/pairs/_orderbook.html.slim
.orderbook
  .ask
    .title
      | ASK
    .price
      | Price
    .size
      | Size
    -orderbook_asks.each do |ask|
      .price =ask['price']
      .size  =ask['size']
  .bid
    .title
      | BID
    .price
      | Price
    .size
      | Size
    -orderbook_bids.each do |bid|
      .price =bid['price']
      .size  =bid['size']

app/views/pairs/_trades.html.slim
.trade
  .trade_row
    .trade_id
      | ID
    .trade_price
      | PRICE
    .trade_quantity
      | QUANTITY
    .trade_side
      | SIDE
    .trade_timestamp
      | TIMESTAMP
  -trades.each do |trade|
    .trade_row
      .trade_id        =trade.trade_id
      .trade_price     =trade.price
      .trade_quantity  =trade.quantity
      .trade_side      =trade.side
      .trade_timestamp =trade.timestamp

app/views/pairs/candles.html.slim
.back =link_to '<-- На главную', pairs_path
h4 История торгов валютной пары #{@pair.symbols}
table.table.table-hover
  th Дата
  th Открытие
  th Закрытие
  th Минимум
  th Максимум
  th Объём базовой валюты
  th Объём котируемой валюты
  - @candles.each do |candle|
    tr
      td=candle.timestamp
      td=candle.open
      td=candle.close
      td=candle.min
      td=candle.max
      td=candle.volume
      td=candle.volumeQuote

app/views/pairs/index.html.slim
table.table.table-hover
  th Наименование пары
  th Базовая валюта
  th Котируемая валюта
  th Увеличение количества
  th Шаг цены
  th Ставка по умолчанию
  th Стандартная ставка для рыночных сделок
  th Валюта ставки
  th Истроия
  -@pairs.each do |pair|
    tr class=pair['symbols']
      td=link_to pair['symbols'], pair_path(pair)
      td=pair['baseCurrency']
      td=pair['quoteCurrency']
      td=pair['quantityIncrement']
      td=pair['tickSize']
      td=pair['takeLiquidityRate']
      td=pair['provideLiquidityRate']
      td=pair['feeCurrency']
      td=link_to 'История торгов', candles_pair_path(pair)

app/views/pairs/show.html.slim
.topdiv
  .back = link_to ' <--- На главную', pairs_path
  h4.pair_title
    | Валютная пара
    = " #{@pair.symbols}"
  .history =link_to 'История торгов пары', candles_pair_path(@pair)

ul.nav.nav-tabs role="tablist"
  li role="presentation"
    a aria-controls="orderbook" data-toggle="tab" href="#orderbook" role="tab"  Orderbook
  li role="presentation"
    a aria-controls="trades" data-toggle="tab" href="#trades" role="tab"  Trades

/! Tab panes
.tab-content
  /!  Orderbook
  #orderbook.tab-pane role="tabpanel"
    = render partial="orderbook", orderbook_asks: @pair.orderbook_asks, orderbook_bids: @pair.orderbook_bids
  /!Trades
  #trades.tab-pane role="tabpanel"
    = render partial="trades", trades: @pair.trades